general {
    lock_cmd = ~/.config/hypr/scripts/quickshell-lock
    inhibit_sleep = 3
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}
