#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_workspaces = 24
    gaps_in = 2
    gaps_out = 24
    border_size = 2
    col.active_border = rgba(818a9cff)
    col.inactive_border = rgba(393c44dd)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 16
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 24
        render_power = 3
        color = rgba(00000055)
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = false
        noise = 0.01
        contrast = 0.9
        brightness = 0.85
    }
}

animations {
    enabled = true
    bezier = snap, 0.05, 0.9, 0.1, 1.0
    animation = windows, 1, 0.4, snap, popin 95%
    animation = border, 1, 0.4, snap
    animation = fade, 1, 0.4, snap
    animation = workspaces, 1, 0.6, snap, slide
    animation = layers, 1, 0.4, snap
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
}

cursor {
    no_hardware_cursors = true
}
