#############
### INPUT ###
#############

input {
    kb_layout = es
    kb_options = lv3:switch
    follow_mouse = 1
    sensitivity = 0
    accel_profile = adaptive
    repeat_rate = 18
    repeat_delay = 650

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
        scroll_factor = 1.0
    }
}


device {
    name = razer-razer-viper-ultimate
    sensitivity = 0
    accel_profile = flat
}

device {
    name = syna328b:00-06cb:cd50-mouse
    sensitivity = 0.22
    accel_profile = flat
}

gestures {
    workspace_swipe_distance = 130
    workspace_swipe_cancel_ratio = 0.15
    workspace_swipe_min_speed_to_force = 12
}

gesture = 3, horizontal, workspace
