#############
### INPUT ###
#############

input {
    kb_layout = es
    kb_options = lv3:switch
    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat
    repeat_rate = 25
    repeat_delay = 500

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
        scroll_factor = 1
    }
}

device {
    name = razer-razer-viper-ultimate
    sensitivity = -0.1
    accel_profile = flat
}

device {
    name = syna32ee:00-06cb:cfc5-touchpad
    sensitivity = 0
    accel_profile = adaptive
    natural_scroll = true
    tap-to-click = true
}

gesture = 3, horizontal, workspace
