################
### PROGRAMS ###
################

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus --new-window
$menu = ~/.config/hypr/scripts/launcher-toggle.sh
$runMenu = rofi -show run
$clipboardMenu = qs ipc call clipboard toggle
$powerMenu = ~/.config/hypr/scripts/power-menu
$snap = ~/.config/hypr/scripts/gnome-snap
