################
### PROGRAMS ###
################

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus --new-window
$menu = rofi -show drun
$runMenu = rofi -show run
$clipboardMenu = ~/.config/hypr/scripts/cliphist-menu
$powerMenu = ~/.config/hypr/scripts/power-menu
$snap = ~/.config/hypr/scripts/gnome-snap
