
# vim:ft=kitty
## name: Cherry Midnight Modern
## author: nullxception (enhanced)
## license: GPLv3
## blurb: A refined, minimalist take on the Cherry Midnight theme

# Platform
linux_display_server     wayland

# Window
hide_window_decorations  yes
window_padding_width     6
background_opacity       0.8
confirm_os_window_close  0
resize_in_steps          yes
# Blur is provided by the compositor.
# background_blur        32

# Typography
font_size                11.5

# Rendering
sync_to_monitor          yes
repaint_delay            8
input_delay              2
enable_audio_bell        no
mouse_hide_wait          1.0

# Theme
foreground               #c0c6e2
background               #000000
selection_foreground     #0c0c12
selection_background     #c0c6e2
url_color                #73a9ff
url_style                curly

color0                   #0a0e1a
color1                   #d64c78
color2                   #47f0a3
color3                   #e0ec80
color4                   #5074f2
color5                   #a064f5
color6                   #57dbf7
color7                   #d6dcff
color8                   #374060
color9                   #f27ca2
color10                  #70ffc5
color11                  #f3ffa3
color12                  #80a0ff
color13                  #c28cff
color14                  #8ef2ff
color15                  #ffffff

# Font size shortcuts
map ctrl+shift+period    increase_font_size
map ctrl+shift+comma     decrease_font_size
map ctrl+shift+0         reset_font_size

# Clipboard
map ctrl+c               copy_to_clipboard
map ctrl+v               paste_from_clipboard
map ctrl+insert          copy_to_clipboard
map shift+insert         paste_from_clipboard

# Shell-like editing
map ctrl+backspace       send_text all \x17
map ctrl+delete          send_text all \x1bd

# Interrupt
map esc                  send_text all \x03
